

name: Build Container Image

#on:
#  push:
#    branches: [ $default-branch ]
#  pull_request:
#    branches: [ $default-branch ]
on: [push]

jobs:

  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Installing dependencies using npm
        run: npm install
      - name: Generate static CSS files using sass
        run: npm run css-build
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)