name: Build and Publish Container Image

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:

  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Installing dependencies using npm
        run: npm install

      - name: Generate web build
        run: npm run web-build

      - name: Log into registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          username: cmeury
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: cmeury/bread-bucket

      - name: Build and push Docker image
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          push: true
          context: .
          tags: cmeury/bread-bucket:latest
          labels: ${{ steps.meta.outputs.labels }}
